kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: saksbehandlervarsling-api
  namespace: {{namespace}}
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/saksbehandlervarsling-api/saksbehandlervarsling-api:{{version}}
  ingresses:
    - https://saksbehandlervarsling-api-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/saksbehandlervarsling-api
  webproxy: true
  port: 8080
  prometheus:
    enabled: true
    path: saksbehandlervarsling-api/internal/prometheus
  liveness:
    path: saksbehandlervarsling-api/internal/isAlive
    initialDelay: 30
  readiness:
    path: saksbehandlervarsling-api/internal/isReady
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  envFrom:
    - configmap: pto-config
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvsaksbehandlervarsling-api
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/preprod/fss/saksbehandlervarsling-api/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault
