
CREATE TABLE VARSEL (
    ID                      BIGSERIAL PRIMARY KEY NOT NULL,
    NAVN                    VARCHAR(100) NOT NULL,
    TITTEL                  VARCHAR(250) NOT NULL,
    BESKRIVELSE             TEXT NOT NULL,
    DATO_OPPRETTET          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OPPRETTET_AV            VARCHAR(100) NOT NULL
);

CREATE TABLE VARSLING (
    ID                      BIGSERIAL PRIMARY KEY NOT NULL,
    SAKSBEHANDLER_ID        VARCHAR(10) NOT NULL,
    VARSEL_ID               BIGINT NOT NULL,
    ER_LEST                 BOOLEAN NOT NULL DEFAULT false,
    DATO_LEST               TIMESTAMP,
    FOREIGN KEY (VARSEL_ID) REFERENCES VARSEL(ID)
);

CREATE INDEX VARSLING_SAKSBEHANDLER_ID_IDX ON VARSLING(SAKSBEHANDLER_ID);

CREATE TABLE ALARM (
    ID                      BIGSERIAL PRIMARY KEY NOT NULL,
    SAKSBEHANDLER_ID        VARCHAR(10) NOT NULL,
    VARSEL_ID               BIGINT NOT NULL,
    DATO_SKAL_VARSLES       TIMESTAMP NOT NULL,
    FOREIGN KEY (VARSEL_ID) REFERENCES VARSEL(ID)
);

CREATE INDEX ALARM_DATO_SKAL_VARSLES_IDX ON ALARM(DATO_SKAL_VARSLES);

